---
title: "Kauliukai"
author: "Danielius Rimas"
date: '2016 m spalis 14 d '
output: html_document
---
Du zaidejai zaidzia toki zaidima. Pirmasis Zaidejas meta tris kauliukus ir fiksuoja iskritusiu tasku suma. Antrasis Zaidejas ridena du kauliukus ir skaiciuoja iskritusiu tasku suma. Laimi tas Zaidejas, kurio tasku suma yra didesne. Jeigu tasku sumos yra lygios, tai eksperimentas kartojamas is naujo (ir taip kartojama tol, kol galiausiai nustatomas laimetojas). Kokia tikimybe laimeti pirmajam zaidejui?

#####tikimybei rasti eksperimenta kartosime 10^5 kartu
n <- 10^5

#####kintamasis while ciklui
i <- 1

#####pirmojo zaidejo tasku sumos vektorius
pirmas_zaidejas <- c(rep(0, n))

#####antrojo zaidejo tasku sumos vektorius
antras_zaidejas <- c(rep(0, n))

#####pirmojo zaidejo laimejimu skaicius
laim_sk <- 0

#####eksperimenta kartosime iki n laimejimu
  while(i <= n) {

    #pirmojo zaidejo iskritusiu akuciu suma, metant kauliukus i-aji karta
    pirmas_zaidejas[i] <- sum(sample(1:6, 3, replace = TRUE))

    #antrojo zaidejo iskritusiu akuciu suma, metant kauliukus i-aji karta
    antras_zaidejas[i] <- sum(sample(1:6, 2, replace = TRUE))
    
    #atvejis kai laimi pirmas zaidejas
      if(pirmas_zaidejas[i] > antras_zaidejas[i]) {
    #eksperimento kartoti nebereiks
        i = i+1
    #pirmasis zaidejas laimi
        laim_sk = laim_sk+1
        }
        
    #atvejis kai laimi antras zaidejas
      else if(pirmas_zaidejas[i] < antras_zaidejas[i]) {
    #eksperimento kartoti nebereiks
        i = i+1
        }
    
    #atvejis kai abu zaidejai gauna po tiek pat tasku
      else {
    #kartojame eksperimenta
        i = i
        }
}

#####apskaiciuojame tikimybe pirmam zaidejui laimeti
tikimybe <- laim_sk/n

#####Saltiniai: https://stat.ethz.ch/R-manual/R-devel/library/base/html/sample.html, https://stat.ethz.ch/R-manual/R-devel/library/base/html/rep.html