---
title: "Moneta"
author: "Danielius Rimas"
date: '2016 m spalis 14 d '
output: html_document
---
Tarkime metama moneta. Jeigu iskrenta herbas, tai laimite $12$ EUR. Jeigu skaicius, tai pralosiate $10$ EUR. Bus zaidziama $100$ kartu ir gauti rezultatai sumuojami. Kokia tikimybe jums tureti teigiama balansa po $100$ kartu? Koks balanso pasikliautinis $95%$ intervalas? Kaip atrodo balanso tankis?

#####tikimybei gauti bandyma atliksime 10^5 kartu 
n <- 10^5

#####visi atlikti bandymai ir gauti balansai
visi_balansai <- replicate(n, sum(sample(c(12, -10), 100, replace = TRUE)))

#####susirandame teigiamus balansus
teig_balansai <- visi_balansai[visi_balansai > 0]

#####apskaiciuojame tikimybe tureti teigiama balansa
tikimybe <- length(teig_balansai)/n

#####Apskaiciuojame apatini pasikliautinojo intervalo rezi
apatinis <- mean(visi_balansai) - qt(0.975, df=n-1)*(sd(visi_balansai)/sqrt(n))

#####Apskaiciuojame virsutini pasikliautinojo intervalo rezi
virsutinis <- mean(visi_balansai) + qt(0.975, df=n-1)*(sd(visi_balansai)/sqrt(n))

#####Balanso tankis atrodo taip

d <- density(visi_balansai)

plot(d, main = "Balanso tankis")

polygon(d, col = "red", border = "red")

#####Saltiniai: http://www.cyclismo.org/tutorial/R/confidence.html, http://www.statmethods.net/graphs/density.html, R help, https://stat.ethz.ch/R-manual/R-devel/library/base/html/lapply.html

